
import { Match } from '../types/matches';

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    homeTeam: 'Morocco',
    awayTeam: 'Spain',
    date: '2030-06-10',
    time: '20:00',
    stadium: 'Grand Stade de Casablanca',
    city: 'Casablanca',
    group: 'A',
    status: 'scheduled',
  },
  {
    id: 'match-2',
    homeTeam: 'France',
    awayTeam: 'Brazil',
    date: '2030-06-11',
    time: '17:00',
    stadium: 'Stade de Marrakech',
    city: 'Marrakech',
    group: 'B',
    status: 'scheduled',
  },
  {
    id: 'match-3',
    homeTeam: 'Argentina',
    awayTeam: 'Germany',
    date: '2030-06-12',
    time: '14:00',
    stadium: 'Grand Stade de Tanger',
    city: 'Tangier',
    group: 'C',
    status: 'scheduled',
  },
  {
    id: 'match-4',
    homeTeam: 'England',
    awayTeam: 'Portugal',
    date: '2030-06-12',
    time: '20:00',
    stadium: 'Stade Moulay Abdallah',
    city: 'Rabat',
    group: 'D',
    status: 'scheduled',
  },
  {
    id: 'match-5',
    homeTeam: 'Belgium',
    awayTeam: 'Netherlands',
    date: '2030-06-13',
    time: '17:00',
    stadium: 'Grand Stade d\'Agadir',
    city: 'Agadir',
    group: 'E',
    status: 'scheduled',
  },
  {
    id: 'match-6',
    homeTeam: 'Italy',
    awayTeam: 'Uruguay',
    date: '2030-06-14',
    time: '14:00',
    stadium: 'Stade de Fès',
    city: 'Fez',
    group: 'F',
    status: 'scheduled',
  },
];
