
import { Stadium } from '../types/stadiums';

export const mockStadiums: Stadium[] = [
  {
    id: 'grand-stade-casablanca',
    name: 'Grand Stade de Casablanca',
    city: 'Casablanca',
    capacity: 93000,
    image: '/placeholder.svg',
    status: 'Under Construction',
    progress: 65,
    description: 'The Grand Stade de Casablanca will be the crown jewel of Morocco\'s World Cup hosting, with a planned capacity of 93,000 spectators. This ultramodern arena will host the opening ceremony, several group matches, a semi-final, and the final match. The stadium features a distinctive Moroccan architectural design with a partially retractable roof and state-of-the-art facilities.',
    features: ['Retractable roof', 'VIP lounges', '360° screens', 'Smart seating', 'FIFA Elite Stadium status'],
    matches: 8,
    startDate: 'June 10, 2030',
    coordinates: [33.5731, -7.5898],
  },
  {
    id: 'stade-moulay-abdallah',
    name: 'Stade Moulay Abdallah',
    city: 'Rabat',
    capacity: 52000,
    image: '/placeholder.svg',
    status: 'Renovation Planned',
    progress: 30,
    description: 'Located in Morocco\'s capital city, the Stade Moulay Abdallah is undergoing extensive renovations to meet FIFA\'s standards for the 2030 World Cup. The renovations will increase seating capacity to 52,000 and modernize all facilities while preserving the stadium\'s historic character. The stadium will host group stage matches and a Round of 16 game.',
    features: ['Enhanced acoustics', 'Improved player facilities', 'New media center', 'Expanded VIP areas'],
    matches: 5,
    startDate: 'June 12, 2030',
    coordinates: [34.0209, -6.8416],
  },
  {
    id: 'grand-stade-agadir',
    name: 'Grand Stade d\'Agadir',
    city: 'Agadir',
    capacity: 45480,
    image: '/placeholder.svg',
    status: 'Operational',
    progress: 100,
    description: 'The Grand Stade d\'Agadir is a modern stadium completed in 2013 with a distinctive crescent-moon shape inspired by the nearby Atlas Mountains. With a capacity of 45,480, this coastal venue will host group stage matches. Its location offers visiting fans an opportunity to combine football with beach activities in one of Morocco\'s most popular tourist destinations.',
    features: ['Natural grass pitch', 'Energy-efficient design', 'Panoramic city views', 'Athletic track'],
    matches: 4,
    startDate: 'June 14, 2030',
    coordinates: [30.4078, -9.5981],
  },
  {
    id: 'stade-marrakech',
    name: 'Stade de Marrakech',
    city: 'Marrakech',
    capacity: 45240,
    image: '/placeholder.svg',
    status: 'Operational',
    progress: 100,
    description: 'The Stade de Marrakech, set against the backdrop of the Atlas Mountains, is a multi-purpose stadium that will showcase Morocco\'s cultural heritage during the World Cup. With a capacity of 45,240, it will host group stage matches and a Round of 16 game. The stadium combines modern amenities with traditional Moroccan design elements such as mosaic tilework and geometric patterns.',
    features: ['Hybrid grass system', '360° fan zone', 'Cultural exhibition space', 'Traditional design elements'],
    matches: 5,
    startDate: 'June 12, 2030',
    coordinates: [31.6295, -8.0056],
  },
  {
    id: 'grand-stade-tanger',
    name: 'Grand Stade de Tanger',
    city: 'Tangier',
    capacity: 65000,
    image: '/placeholder.svg',
    status: 'Expansion Planned',
    progress: 50,
    description: 'The Grand Stade de Tanger is undergoing significant expansion to increase its capacity to 65,000 for the World Cup. Its strategic location near the Strait of Gibraltar makes it easily accessible for European fans. The stadium will feature a unique design inspired by the region\'s maritime heritage and will host group stage matches, a Round of 16 game, and a quarter-final match.',
    features: ['Expanded seating', 'Maritime design theme', 'Mediterranean views', 'Advanced cooling system'],
    matches: 6,
    startDate: 'June 13, 2030',
    coordinates: [35.7595, -5.8040],
  },
  {
    id: 'stade-fes',
    name: 'Stade de Fès',
    city: 'Fez',
    capacity: 45000,
    image: '/placeholder.svg',
    status: 'Renovation Planned',
    progress: 40,
    description: 'Located in the historic city of Fez, this stadium is being renovated to reflect the city\'s status as a cultural and intellectual center. The renovations will boost capacity to 45,000 and improve all facilities while incorporating elements inspired by the city\'s famous medina. The stadium will host group stage matches and will showcase Morocco\'s oldest imperial city to visiting fans.',
    features: ['Traditional architecture', 'Modern amenities', 'Cultural heritage displays', 'Improved accessibility'],
    matches: 4,
    startDate: 'June 13, 2030',
    coordinates: [34.0181, -4.9774],
  },
];
